In [957]:
import aerofiles
import pandas as pd
import numpy as np
import datetime

with open("guillaumetiti-06-07-2022-13h-15h.igc", "r") as f:
    decoded_igc = aerofiles.igc.Reader().read(f.readlines())

In [958]:
latitudes = np.array([record['lat'] for record in decoded_igc['fix_records'][1]])
longitudes = np.array([record['lon'] for record in decoded_igc['fix_records'][1]])
altitudes= np.array([record['gps_alt'] for record in decoded_igc['fix_records'][1]])
dates = np.array([record['time'] for record in decoded_igc['fix_records'][1]])

In [959]:
timestamps = np.array([datetime.datetime.combine(datetime.date(2020,1,1), time) for time in dates])
differences = np.diff(timestamps)
vfunc = np.vectorize(lambda x: x.total_seconds())
delta = vfunc(differences).astype(int)

In [960]:
def haversine_np(lon1, lat1, lon2, lat2):
    """
    Calculate the great circle distance between two points
    on the earth (specified in decimal degrees)

    All args must be of equal length.    

    """
    lon1, lat1, lon2, lat2 = map(np.radians, [lon1, lat1, lon2, lat2])

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = np.sin(dlat/2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2.0)**2

    c = 2 * np.arcsin(np.sqrt(a))
    km = 6367 * c
    return km

In [961]:
lat1 = np.array(latitudes)
lat2 = lat1[1:]
lat1 = lat1[0:-1]
long1 = np.array(longitudes)
long2 = long1[1:]
long1 = long1[0:-1]

In [962]:
km = haversine_np(long1,lat1,long2,lat2)

In [963]:
v = (km / delta) * 3600

In [905]:
v.max()

35.690945100338475

In [964]:
import math

def direction(lat1, lon1, lat2, lon2):
    dLon = lon2 - lon1
    y = np.sin(dLon) * np.cos(lat2)
    x = np.cos(lat1) * np.sin(lat2) - np.sin(lat1) * np.cos(lat2) * np.cos(dLon)
    brng = np.arctan2(y, x)
    brng = np.degrees(brng)
    brng = (brng + 360) % 360
    brng = 360 - brng # count degrees counter-clockwise - remove to make clockwise
    index = ((brng + 11.25) / 22.5).astype(int) % 16
    return index

In [965]:
indexOfDirection = direction(lat1, long1, lat2, long2)

In [966]:
def getDirection(x):
    return ["N", "NNE", "NE", "ENE", "E", "ESE", "SE", "SSE",
                  "S", "SSW", "SW", "WSW", "W", "WNW", "NW", "NNW"][x]

In [967]:
vfunc = np.vectorize(getDirection)
directions = vfunc(indexOfDirection)

In [968]:
df = pd.DataFrame({'vitesse': v, 'direction': directions, 'km': km, 'delta': delta, 'timestamps': timestamps[1:], 'altitude': altitudes[1:], 'latitude': latitudes[1:], 'longitude': longitudes[1:]})

In [928]:
df[['timestamps','vitesse','direction','altitude']][0:43] #.sort_values(by=['vitesse'],ascending=False)

            timestamps    vitesse direction  altitude
0  2020-01-01 12:58:12  18.446505        SE       166
1  2020-01-01 12:58:13  29.559123        SE       163
2  2020-01-01 12:58:14  31.624258        SE       163
3  2020-01-01 12:58:15  21.732506       SSE       164
4  2020-01-01 12:58:16  21.732510       SSE       165
5  2020-01-01 12:58:17  20.002520         S       164
6  2020-01-01 12:58:18  20.448745       SSE       163
7  2020-01-01 12:58:19  27.990927       SSE       163
8  2020-01-01 12:58:20  20.448748       SSE       162
9  2020-01-01 12:58:21  21.732529       SSE       162
10 2020-01-01 12:58:22  14.384378       ESE       162
11 2020-01-01 12:58:23  12.745773         E       162
12 2020-01-01 12:58:24  21.601639       ENE       161
13 2020-01-01 12:58:25  27.990932       NNE       160
14 2020-01-01 12:58:26  27.990928       NNW       159
15 2020-01-01 12:58:27  29.559156        NW       158
16 2020-01-01 12:58:28  31.624287        NW       157
17 2020-01-01 12:58:29  35.690945       NNW       157
18 2020-01-01 12:58:30  34.403372       NNW       156
19 2020-01-01 12:58:31  33.607162         N       155
20 2020-01-01 12:58:32  33.607161         N       155
21 2020-01-01 12:58:33  27.990899       NNW       155
22 2020-01-01 12:58:34  33.607159         N       155
23 2020-01-01 12:58:35  33.607158         N       155
24 2020-01-01 12:58:36  27.006299       NNE       154
25 2020-01-01 12:58:37  21.601375       ENE       153
26 2020-01-01 12:58:38  26.348583         E       152
27 2020-01-01 12:58:39  32.592365       ESE       150
28 2020-01-01 12:58:40  31.624161        SE       150
29 2020-01-01 12:58:41  23.718129        SE       149
30 2020-01-01 12:58:42  27.006301       SSE       148
31 2020-01-01 12:58:43  26.670027         S       147
32 2020-01-01 12:58:44  26.670027         S       145
33 2020-01-01 12:58:45  34.403364       SSW       144
34 2020-01-01 12:58:46  27.006305       SSW       144
35 2020-01-01 12:58:47  20.448741       SSW       143
36 2020-01-01 12:58:48  20.448742       SSE       143
37 2020-01-01 12:58:49  13.995458       SSE       143
38 2020-01-01 12:58:50  20.002520         S       142
39 2020-01-01 12:58:51  13.995460       SSW       142
40 2020-01-01 12:58:52   4.248567         W       143
41 2020-01-01 12:58:53   4.248567         W       144
42 2020-01-01 12:58:54   7.906072        SW       144

In [971]:
# def haversine_np(lon1, lat1, lon2, lat2):
distanceFromTakeOf = int(haversine_np(df['longitude'].iloc[0], df['latitude'].iloc[0], df['longitude'].iloc[-1], df['latitude'].iloc[-1]) * 1000)

In [972]:
distanceFromTakeOf

56139

In [945]:
df['longitude'].iloc[0], df['latitude'].iloc[0]

(2.5130833333333333, 50.41655)

In [ ]:
# 50.34338776980154, 2.575899642261151

In [982]:
def passedNearPoint(df, longitude, latitude, distance): 
    tempDf = df.iloc[::60, :].copy() # ne garder qu'un point toute les 60 secondes pour optimiser
    tempDf['distanceFromPoint'] = (haversine_np(tempDf['longitude'], tempDf['latitude'], longitude , latitude) * 1000).astype(int)
    tempDf['isNearPoint'] = tempDf['distanceFromPoint'] < distance
    return len(tempDf[tempDf['isNearPoint']]) > 0

In [984]:
passedNearPoint(df, 2.575899642261151, 50.34338776980154, 3000)

False

In [944]:
df.groupby('direction')['vitesse'].mean().sort_values(ascending=False)

direction
NNW    31.519036
NW     30.591721
NNE    27.498615
SE     26.994435
SSW    23.963467
ESE    23.488371
S      23.336274
SSE    21.726274
ENE    21.601507
E      19.547178
SW      7.906072
W       4.248568
N       3.360716
Name: vitesse, dtype: float64

In [885]:
# First 5 minutes of flight
df = df[0:300].copy()

In [886]:
df['shift_direction_1'] = df['direction'].shift(1)
df['shift_km_1'] = df['km'].shift(1)
df['shift_delta_1'] = df['delta'].shift(1)
df['shift_direction_2'] = df['direction'].shift(2)
df['shift_km_2'] = df['km'].shift(2)
df['shift_delta_2'] = df['delta'].shift(2)

In [887]:
df['equal_direction'] = (
                           (df['direction'] == df['shift_direction_1']) &
                           (df['shift_direction_1'] == df['shift_direction_2'])
                          )

In [888]:
straightFlight = df[df['equal_direction'] == True].copy()

In [889]:
straightFlight['speed'] = (straightFlight['km'] + straightFlight['shift_km_1'] + straightFlight['shift_km_2']) / (straightFlight['delta'] + straightFlight['shift_delta_1'] + straightFlight['shift_delta_2']) * 3600

In [890]:
straightFlight[['direction','speed']].sort_values(by=['speed'], ascending=False)

   direction      speed
35       SSW  27.286137
2         SE  24.519098
9        SSE  23.390734
8        SSE  22.962807
78         N   0.000000
77         N   0.000000
76         N   0.000000
75         N   0.000000
74         N   0.000000
64         N   0.000000
72         N   0.000000
71         N   0.000000
70         N   0.000000
69         N   0.000000
68         N   0.000000
67         N   0.000000
66         N   0.000000
65         N   0.000000
73         N   0.000000
62         N   0.000000
63         N   0.000000
61         N   0.000000
60         N   0.000000
59         N   0.000000
58         N   0.000000
57         N   0.000000
56         N   0.000000
55         N   0.000000
54         N   0.000000
53         N   0.000000
52         N   0.000000
51         N   0.000000
50         N   0.000000
49         N   0.000000
48         N   0.000000
79         N   0.000000

In [897]:
df['delta']

0     2
1     1
2     1
3     1
4     1
     ..
75    1
76    1
77    1
78    1
79    1
Name: delta, Length: 80, dtype: int64